version: '3'

networks:
    book_store_default:
      driver: bridge
      driver_opts:
        com.docker.network.enable_ipv6: "false"
      ipam:
        driver: default
        config:
          - subnet: "172.19.0.0/24"

services:
    postgres:
        image: postgres
        container_name: postgresql
        networks:
            book_store_default:
                ipv4_address: 172.19.0.2
        environment: 
            POSTGRES_USER: "user"
            POSTGRES_PASSWORD: "user"
            POSTGRES_DB: "book_store"
            PGDATA: /var/lib/postgres
        ports:
            - '5432:5432'
        volumes:
            - ./rdb/init.psql:/docker-entrypoint-initdb.d/init.sql
            - postgres:/var/lib/postgres
    main_application:
        build: ./bestofbooks
        container_name: main_application
        depends_on:
            - postgres
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/book_store
        networks:
            book_store_default:
                ipv4_address: 172.19.0.4
        ports:
            - "8080:8080"
volumes:
    postgres:
