# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
###########################
name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    
    steps:
    - uses: actions/checkout@v1
      with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
    #CD
    - name: Add remote origin
      run: |
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    - run: heroku buildpacks:set heroku/java -a ${{ secrets.HEROKU_APP_NAME }}
    - name: Fill Database
      run: heroku pg:psql -a ${{ secrets.HEROKU_APP_NAME }} < rdb/init.psql
    - name: Deploy to Heroku
      run: |
        git push heroku HEAD:master -f
